application:
  default_sps: 50
motors:
  1:
    dir_pin: 20
    initial_position: 0
    inverted: true
    led_pin: 16
    max_deg: 1000
    min_deg: 0
    step_pin: 21
    steps_per_rev: 3200
    steps_per_second: 500
  2:
    dir_pin: 25
    initial_position: 0
    inverted: true
    led_pin: 12
    max_deg: 800
    min_deg: 0
    step_pin: 8
    steps_per_rev: 3200
    steps_per_second: 500
  3:
    dir_pin: 17
    initial_position: 0
    inverted: true
    led_pin: 7
    max_deg: 1000
    min_deg: 0
    step_pin: 27
    steps_per_rev: 3200
    steps_per_second: 500
  4:
    dir_pin: 5
    initial_position: 0
    inverted: true
    led_pin: 1
    max_deg: 1000
    min_deg: 0
    step_pin: 6
    steps_per_rev: 3200
    steps_per_second: 500
